### ISSUE TITLE
Decompile Issues

### ISSUE THREAD

**Issue by BearzRobotics** [Zowja/New-Frontier-Craft#2]
When I went to run the decompile script script I got this out come when it tried to recompile it.
Basically its an library issue, So how do you get theses libraries and were do you put them.

src/minecraft/net/minecraft/client/Minecraft.java:11: error: package org.lwjgl does not exist
import org.lwjgl.LWJGLException;
^

src/minecraft/net/minecraft/client/Minecraft.java:12: error: package org.lwjgl.input does not exist
import org.lwjgl.input.*;
^

src/minecraft/net/minecraft/client/Minecraft.java:13: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.*;
^

src/minecraft/net/minecraft/client/Minecraft.java:14: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.DisplayMode;
^

src/minecraft/net/minecraft/client/Minecraft.java:15: error: package org.lwjgl.util.glu does not exist
import org.lwjgl.util.glu.GLU;
^

src/minecraft/net/minecraft/client/Minecraft.java:83: error: cannot find symbol
throws LWJGLException
^

symbol:   class LWJGLException
location: class Minecraft
src/minecraft/net/minecraft/client/Minecraft.java:198: error: cannot find symbol
throws LWJGLException
^

symbol:   class LWJGLException
location: class Minecraft
src/minecraft/net/minecraft/src/GuiScreen.java:10: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Keyboard;
^

src/minecraft/net/minecraft/src/GuiScreen.java:11: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Mouse;
^

src/minecraft/net/minecraft/src/GuiScreen.java:12: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/Gui.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/OpenGlCapsChecker.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.ContextCapabilities;
^

src/minecraft/net/minecraft/src/OpenGlCapsChecker.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GLContext;
^

src/minecraft/net/minecraft/src/RenderGlobal.java:10: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.ARBOcclusionQuery;
^

src/minecraft/net/minecraft/src/RenderGlobal.java:11: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/EffectRenderer.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderEngine.java:22: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/FontRenderer.java:11: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/LoadingScreenRenderer.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.Display;
^

src/minecraft/net/minecraft/src/LoadingScreenRenderer.java:9: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/EntityRenderer.java:11: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Mouse;
^

src/minecraft/net/minecraft/src/EntityRenderer.java:12: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.*;
^

src/minecraft/net/minecraft/src/EntityRenderer.java:13: error: package org.lwjgl.util.glu does not exist
import org.lwjgl.util.glu.GLU;
^

src/minecraft/net/minecraft/src/GuiAchievement.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiIngame.java:11: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GameSettings.java:9: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Keyboard;
^

src/minecraft/net/minecraft/src/MouseHelper.java:9: error: package org.lwjgl does not exist
import org.lwjgl.LWJGLException;
^

src/minecraft/net/minecraft/src/MouseHelper.java:10: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Cursor;
^

src/minecraft/net/minecraft/src/MouseHelper.java:11: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Mouse;
^

src/minecraft/net/minecraft/src/TextureFX.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiButton.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiParticle.java:10: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/WorldRenderer.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderBlocks.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderList.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/ItemRenderer.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderItem.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/Render.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/ModelRenderer.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/MouseHelper.java:57: error: cannot find symbol
private Cursor cursor;
^

symbol:   class Cursor
location: class MouseHelper
src/minecraft/net/minecraft/src/Tessellator.java:9: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.*;
^

src/minecraft/net/minecraft/src/MapItemRenderer.java:9: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderManager.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/ClippingHelperImpl.java:9: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/EntityFootStepFX.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/EntityPickupFX.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GLAllocation.java:10: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiAchievements.java:10: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Mouse;
^

src/minecraft/net/minecraft/src/GuiAchievements.java:11: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiChat.java:8: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Keyboard;
^

src/minecraft/net/minecraft/src/GuiChest.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiContainer.java:9: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Keyboard;
^

src/minecraft/net/minecraft/src/GuiContainer.java:10: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiCrafting.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiCreateWorld.java:10: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Keyboard;
^

src/minecraft/net/minecraft/src/GuiDispenser.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiEditSign.java:9: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Keyboard;
^

src/minecraft/net/minecraft/src/GuiEditSign.java:10: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiFurnace.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiGameOver.java:9: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiInventory.java:9: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiMainMenu.java:12: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiMultiplayer.java:9: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Keyboard;
^

src/minecraft/net/minecraft/src/GuiRenameWorld.java:9: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Keyboard;
^

src/minecraft/net/minecraft/src/GuiSlot.java:9: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Mouse;
^

src/minecraft/net/minecraft/src/GuiSlot.java:10: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiSleepMP.java:9: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Keyboard;
^

src/minecraft/net/minecraft/src/GuiSlider.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiSlotStats.java:9: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Mouse;
^

src/minecraft/net/minecraft/src/GuiStats.java:9: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/GuiTexturePacks.java:10: error: package org.lwjgl does not exist
import org.lwjgl.Sys;
^

src/minecraft/net/minecraft/src/GuiTexturePackSlot.java:9: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/ModelWolf.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/PanelCrashReport.java:12: error: package org.lwjgl does not exist
import org.lwjgl.Sys;
^

src/minecraft/net/minecraft/src/PanelCrashReport.java:13: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderArrow.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderBiped.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderLiving.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderBoat.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderCreeper.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderEntity.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderFallingSand.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderFireball.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderFish.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderGhast.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderGiantZombie.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderHelper.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderLightningBolt.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderMinecart.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderPainting.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderPlayer.java:8: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderSheep.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderSlime.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderSnowball.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderSpider.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderSquid.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/RenderTNTPrimed.java:7: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/ScreenShotHelper.java:14: error: package org.lwjgl does not exist
import org.lwjgl.BufferUtils;
^

src/minecraft/net/minecraft/src/ScreenShotHelper.java:15: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.GL11;
^

src/minecraft/net/minecraft/src/StatStringFormatKeyInv.java:8: error: package org.lwjgl.input does not exist
import org.lwjgl.input.Keyboard;
^

**Comment by Zowja** [comment]
All of these jars except for the authlib should be in the /lib on this git
